use_frameworks!
platform :ios, '9.0'

target 'Matcha' do
    pod 'EarlGrey'
    target 'MatchaTests' do
        project 'Matcha'
        
        use_frameworks!
        inherit! :search_paths
        
    end
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
